version: '3.8'

services:
  depthai:
    image: luxonis/depthai-library:latest
    command: python3 /depthai-python/examples/ColorCamera/rgb_preview.py # launch cam
    # command: /bin/bash 
    tty: true
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    devices:
      - /dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
    network_mode: host

    # set container hostname 
    # MUST be same as that of your host machine 
    hostname: cleaner  
