version: '3.8'

services:
  arucotag:
    build: 
      context: .  
      dockerfile: Dockerfile 
    image: pomelo925/realsense-aruco:ros-noetic
    container_name: realsense
    command: /bin/bash 
    tty: true  
    network_mode: host
    privileged: true 

    ## accessibility to Intel® RealSense™ 


    ## [IMPORTANT] Change container hostname to that of the host machine's 
    hostname: cleaner  
