version: '3.8'

services:
  arucotag:
    build: 
      context: .  
      dockerfile: Dockerfile 
    image: pomelo925/realsense-aruco:ros-noetic
    container_name: realsense
    command: /bin/bash 
    tty: true  
    network_mode: host
    privileged: true 

    ## accessibility to Intel® RealSense™ 
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority 
    environment:
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
    devices:
      - /dev/bus/usb  # Grant access to USB devices

    ## [IMPORTANT] Change container hostname to that of the host machine's 
    hostname: cleaner  

# roslaunch realsense2_camera rs_camera.launch